### ISSUE TITLE
 Undefined variable: filetype

### ISSUE THREAD

**Issue by vtemian** [PressLabs/autover#10] opened 2015-04-26 18:59 UTC
Using a local instance with `autover` installed this notice appeared:
```Notice: Undefined variable: filetype in /vagrant/wp-content/plugins/autover/autover.php on line 134```

**Comment by zalmanu** [comment] 2015-10-22 10:42
Duplicate of https://github.com/PressLabs/autover/issues/4

**Closed** 2015-10-22 10:43 UTC
